{"uuid": "57dd7cd9-3742-4b76-9076-84b3d3b8513f", "befores": [{"name": "check_light_mode", "status": "failed", "statusDetails": {"message": "AssertionError: Error : Get MQTT syncPilot timeout!\n", "trace": "  File \"C:\\Users\\Ricardo.Lu\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Ricardo.Lu\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 957, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Ricardo.Lu\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 787, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"D:\\workspace\\wiz-automation-test-bitbuckeet\\WizAutomationTest\\Test_Suites\\Steps\\control_lamp_steps.py\", line 832, in check_light_mode\n    mqtt_res = target.mqtt.get_res_mqtt_sync_pilot(light_name)\n  File \"D:\\workspace\\wiz-automation-test-bitbuckeet\\WizAutomationTest\\Wrapper\\wrapper_mqtt.py\", line 406, in get_res_mqtt_sync_pilot\n    assert False, \"Error : Get MQTT syncPilot timeout!\"\n"}, "start": 1608793558677, "stop": 1608793569885}], "start": 1608793558677, "stop": 1608793573223}