{"uuid": "6905b208-1c8a-423e-abff-de1b3be35f06", "befores": [{"name": "make_light_paired", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.\n\n", "trace": "  File \"C:\\workspace\\wiz-automation-test\\WizAutomatedSystemTest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\workspace\\wiz-automation-test\\WizAutomatedSystemTest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\workspace\\wiz-automation-test\\WizAutomatedSystemTest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\workspace\\wiz-automation-test\\WizAutomatedSystemTest\\Test_Suites\\Steps\\pair_lamps_steps.py\", line 195, in make_light_paired\n    target.ui.pairing_process_page.click_done()\n  File \"C:\\workspace\\wiz-automation-test\\WizAutomatedSystemTest\\DUT\\UI\\pairing_process_page.py\", line 175, in click_done\n    self.ui_common.element_location('id', PairingProcessPage.SET_FINISH).click()\n  File \"C:\\workspace\\wiz-automation-test\\WizAutomatedSystemTest\\DUT\\UI\\ui_common.py\", line 155, in element_location\n    return self.driver.find_element_by_id(self.appPackage + ':id/' + element)\n  File \"C:\\Users\\600008165\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 360, in find_element_by_id\n    return self.find_element(by=By.ID, value=id_)\n  File \"C:\\Users\\600008165\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 284, in find_element\n    'value': value})['value']\n  File \"C:\\Users\\600008165\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\600008165\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response\n    raise wde\n  File \"C:\\Users\\600008165\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 24, in check_response\n    super(MobileErrorHandler, self).check_response(response)\n  File \"C:\\Users\\600008165\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1599207579316, "stop": 1599207647471}], "start": 1599207579316, "stop": 1599207648737}